// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8hqCq3K3QcuyR5kFjefZxooFbo7Gu5Gg',
    appId: '1:419332437171:android:7a0616b98a6d12c6b0acc6',
    messagingSenderId: '419332437171',
    projectId: 'online-app-94dd7',
    storageBucket: 'online-app-94dd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeyPea3PU_-eO8v2AY1xeOcfPW_NssFF0',
    appId: '1:419332437171:ios:84a2540258060c78b0acc6',
    messagingSenderId: '419332437171',
    projectId: 'online-app-94dd7',
    storageBucket: 'online-app-94dd7.firebasestorage.app',
    iosBundleId: 'com.example.onlineApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpE554Gph-wZXhxtb2ExCGHCRWp9u8Jwk',
    appId: '1:419332437171:web:82e909222df893c2b0acc6',
    messagingSenderId: '419332437171',
    projectId: 'online-app-94dd7',
    authDomain: 'online-app-94dd7.firebaseapp.com',
    storageBucket: 'online-app-94dd7.firebasestorage.app',
  );

}